default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['POSTGRES_USER'] %>
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: db
  database: app_development
  password: <%= ENV['POSTGRES_PASSWORD'] %>

test:
  <<: *default
  host: db
  database: app_test
  password: <%= ENV['POSTGRES_PASSWORD'] %>
