services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/
        - action: rebuild
          path: ./package.json
    volumes:
      - front_node_modules:/app/node_modules
    command: npm run dev -- -p 4000
    ports:
      - '4000:4000'
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${USER_PASS}
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${USER_NAME}
      POSTGRES_PASSWORD: ${USER_PASS}
      POSTGRES_DB: app_development
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  front_node_modules:
  postgres_data:
